/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlVistaTerminal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modelo.Caseta;

/**
 *
 * @author JORGE
 */
public class VistaTerminal extends javax.swing.JFrame implements ActionListener{

    JButton[][] botones;
    ControlVistaTerminal controlVT;

    /**
     * Creates new form VistaAdmiTerminal
     */
    public VistaTerminal() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Vista Terminal");
        botones = new JButton[3][];
        botones[0] = new JButton[5];
        botones[1] = new JButton[2];
        botones[2] = new JButton[4];
        controlVT = new ControlVistaTerminal();
        dibujarBotones();
        pintarBotones();
    }

     public void dibujarBotones() {
        int separado = 70;
        int ancho = 100;
        int alto = 100;
       
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j] = new JButton();
                if (i == 1) {
                    botones[i][j].setBounds(ancho * j + separado + 
                            (j >= 1 ? 100*3 : 0),
                            alto * i + separado,
                            ancho, alto);
                } else if(i == 2 && j >= 2){
                    botones[i][j].setBounds(ancho * j + separado +
                            (j >= 2 ? 100 : 0),
                            alto * i + separado + (i >= 1 ? 100 : 0),
                            ancho, alto);
                }else{
                    botones[i][j].setBounds(ancho * j + separado,
                            alto * i + separado, ancho, alto);
                }

                botones[i][j].addActionListener(this);
                this.add(botones[i][j]);
            }
        }
    }
     
         public void pintarBotones() {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
               Caseta caseta = controlVT.entregarCaseta(i, j);
                if(caseta.isEnUso()){
                    botones[i][j].setBackground(Color.BLUE);
               }else{
                    botones[i][j].setBackground(Color.WHITE);
                }
            }
        }
    }

    public void actionPerformed(ActionEvent e) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                if (e.getSource().equals(botones[i][j])) {
                    Caseta caseta = controlVT.entregarCaseta(i, j);
                    if(!caseta.isEnUso()){
                    VistaGestionCaseta vistaGC = new VistaGestionCaseta(caseta);
                    vistaGC.setVisible(true);
                    this.dispose();
                    }else{
                        VistaInfoCaseta vistaIC = new VistaInfoCaseta(caseta);
                        vistaIC.setVisible(true);
                        this.dispose();
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(491, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaLogin vistaL = new VistaLogin();
        vistaL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    // End of variables declaration//GEN-END:variables
}
