/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlVistaFlota;
import java.awt.event.ActionEvent;
import modelo.AdmiFlota;
import modelo.Caseta;

/**
 *
 * @author JORGE
 */
public class VistaFlota extends javax.swing.JFrame {
    AdmiFlota admiFlota;
    Caseta caseta;
    ControlVistaFlota controlVF;
    /**
     * Creates new form VistaFlota
     */
    public VistaFlota(AdmiFlota admiFlota) {
        initComponents();
        setLocationRelativeTo(this);
        this.controlVF = new ControlVistaFlota();
        setTitle("Ventana administrador de flota: " + admiFlota.getNombre());
        this.admiFlota = admiFlota;
        this.caseta = controlVF.obtenerCaseta(admiFlota);
        lblNombre.setText("AdmiFlota: " + admiFlota.getNombre());
        lblId.setText("Id: " + admiFlota.getId());
        lblCaseta.setText("Caseta: " + caseta.getEmpresa().getNombre());
        lblPlazas.setText("Plazas: " + caseta.getPlazas());
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke("ESCAPE"), "regresar");
        getRootPane().getActionMap().put("regresar", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnRegresar.doClick(); // Simula un clic en el botón "Regresar"
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGestionViajes = new javax.swing.JButton();
        btnVentaTiquetes = new javax.swing.JButton();
        btnValidarReservas = new javax.swing.JButton();
        btnDevoluciones = new javax.swing.JButton();
        lblCaseta = new javax.swing.JLabel();
        lblPlazas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("jLabel1");

        lblId.setText("jLabel1");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jButton1.setText("Gestion de buses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGestionViajes.setText("Gestion de Viajes");
        btnGestionViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionViajesActionPerformed(evt);
            }
        });

        btnVentaTiquetes.setText("Venta de tiquetes");
        btnVentaTiquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaTiquetesActionPerformed(evt);
            }
        });

        btnValidarReservas.setText("Validar reservas");
        btnValidarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarReservasActionPerformed(evt);
            }
        });

        btnDevoluciones.setText("Devoluciones");
        btnDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesActionPerformed(evt);
            }
        });

        lblCaseta.setText("jLabel1");

        lblPlazas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(67, 67, 67)
                                .addComponent(lblId)
                                .addGap(53, 53, 53)
                                .addComponent(lblCaseta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPlazas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentaTiquetes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValidarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblId)
                    .addComponent(lblCaseta)
                    .addComponent(lblPlazas))
                .addGap(129, 129, 129)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnGestionViajes)
                .addGap(18, 18, 18)
                .addComponent(btnVentaTiquetes)
                .addGap(18, 18, 18)
                .addComponent(btnValidarReservas)
                .addGap(18, 18, 18)
                .addComponent(btnDevoluciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaLogin vistaL = new VistaLogin();
        vistaL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VistaGestionBuses vistaGB = new VistaGestionBuses(caseta, admiFlota);
        vistaGB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGestionViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionViajesActionPerformed
        // TODO add your handling code here:
        VistaGestionViajes vistaV = new VistaGestionViajes(caseta, admiFlota);
        vistaV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGestionViajesActionPerformed

    private void btnVentaTiquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaTiquetesActionPerformed
        // TODO add your handling code here:
        VistaVentaTiquetes vistaVT = new VistaVentaTiquetes(caseta, admiFlota);
        vistaVT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentaTiquetesActionPerformed

    private void btnValidarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarReservasActionPerformed
        // TODO add your handling code here:
        VistaValidarReservas vistaVR = new VistaValidarReservas(caseta, admiFlota);
        vistaVR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnValidarReservasActionPerformed

    private void btnDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesActionPerformed
        // TODO add your handling code here:
        VistaDevoluciones vistaD = new VistaDevoluciones(caseta, admiFlota);
        vistaD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDevolucionesActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevoluciones;
    private javax.swing.JButton btnGestionViajes;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnValidarReservas;
    private javax.swing.JButton btnVentaTiquetes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCaseta;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlazas;
    // End of variables declaration//GEN-END:variables
}
