/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlHistorialDevoluciones;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Cliente;
import modelo.Devolucion;

/**
 *
 * @author JORGE
 */
public class VistaHistorialDevoluciones extends javax.swing.JFrame {

    Cliente cliente;
    ControlHistorialDevoluciones controlHD;
    /**
     * Creates new form VistaHistorialDevoluciones
     */
    public VistaHistorialDevoluciones(Cliente cliente) {
        initComponents();
        setLocationRelativeTo(this);
        this.cliente = cliente;
        lblCliente.setText("Cliente: " + cliente.getNombre());
        lblId.setText("Id: " + cliente.getId());
        lblPuntos.setText("Puntos: " + cliente.getPuntos());
        lblNotificaciones.setText("Notifs: " + cliente.getNotificaciones().size());
        controlHD = new ControlHistorialDevoluciones(cliente);
        llenarTablaDevoluciones();
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke("ESCAPE"), "regresar");
        getRootPane().getActionMap().put("regresar", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnRegresar.doClick(); // Simula un clic en el botón "Regresar"
            }
        });
    }

    private void llenarTablaDevoluciones() {

        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Viaje",
            "FechaReserva", "Cliente"},
                controlHD.obtenerDevoluciones(cliente).size());
        tablaDevoluciones.setModel(model);
        TableModel modelDevolucion = tablaDevoluciones.getModel();
        for (int i = 0; i < controlHD.obtenerDevoluciones(cliente).size(); i++) {
            Devolucion devolucion = controlHD.obtenerDevoluciones(cliente).get(i);
            modelDevolucion.setValueAt(devolucion.getId(), i, 0);
            modelDevolucion.setValueAt(devolucion.getViaje(), i, 1);
            modelDevolucion.setValueAt(devolucion.getFechaCompra(), i, 2);
            modelDevolucion.setValueAt(devolucion.getCliente(), i, 3);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDevoluciones = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblNotificaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Viaje", "Fecha compra", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDevoluciones);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Devoluciones");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblCliente.setText("jLabel4");

        lblId.setText("jLabel4");

        lblPuntos.setText("jLabel4");

        lblNotificaciones.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRegresar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente)
                .addGap(120, 120, 120)
                .addComponent(lblId)
                .addGap(131, 131, 131)
                .addComponent(lblPuntos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(lblNotificaciones)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblId)
                    .addComponent(lblPuntos)
                    .addComponent(lblNotificaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaCliente vistaC = new VistaCliente(cliente);
        vistaC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNotificaciones;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JTable tablaDevoluciones;
    // End of variables declaration//GEN-END:variables
}
