/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.ControlGestionViajes;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.AdmiFlota;
import modelo.Bus;
import modelo.Caseta;
import modelo.Viaje;

/**
 *
 * @author JORGE
 */
public class VistaGestionViajes extends javax.swing.JFrame {
    Caseta caseta;
    AdmiFlota admiFlota;
    ControlGestionViajes controlGV;
    /**
     * Creates new form VistaGestionViajes
     */
    public VistaGestionViajes(Caseta caseta, AdmiFlota admiFlota) {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Gestion de viajes");
        this.caseta = caseta;
        this.admiFlota = admiFlota;
        this.controlGV = new ControlGestionViajes(caseta);
        llenarTabla();
        comboBox();
        listenerTabla();
        lblAdminFlota.setText("AdminFlota: " + admiFlota.getNombre());
        lblId.setText("Id: " + admiFlota.getId());
        lblCaseta.setText("Caseta: " + caseta.getEmpresa().getNombre());
        lblPlazas.setText("Plazas: " + caseta.getPlazas());
        dateCreacion.setEnabled(false);
    }
    
    private void llenarTabla(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"Origen",
            "Destino","FechaCreacion","HoraSalida","FechaLlegada","HoraLlegada",
            "Bus","ValorUnidad","id"},controlGV.getCaseta().getViajes()
                    .size());
        tablaViajes.setModel(model);
        TableModel modelViaje = tablaViajes.getModel();
        for (int i = 0; i < controlGV.getCaseta().getViajes().size(); i++) {
            Viaje viaje = controlGV.getCaseta().getViajes().get(i);
            modelViaje.setValueAt(viaje.getOrigen(), i, 0);
            modelViaje.setValueAt(viaje.getDestino(), i, 1);
            modelViaje.setValueAt(viaje.getFechaCreacion(), i, 2);
            modelViaje.setValueAt(viaje.getHoraSalida(), i, 3);
            modelViaje.setValueAt(viaje.getFechaLLegada(), i, 4);
            modelViaje.setValueAt(viaje.getHoraLlegada(), i, 5);
            modelViaje.setValueAt(viaje.getBus(), i, 6);
            modelViaje.setValueAt(viaje.getValorUnidad(), i, 7);
            modelViaje.setValueAt(viaje.getId(), i, 8);
        }
    }

    private void listenerTabla(){
        ListSelectionModel model = tablaViajes.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(tablaViajes.getSelectedRow()!=-1){
//                    txtIdViaje.setText((String)tablaViajes.getValueAt(tablaViajes.getSelectedRow(), 8));
                      txtIdViaje.setText(String.valueOf(tablaViajes.getValueAt(tablaViajes.getSelectedRow(), 8)));
                }
            }
           
        });
    }
    
    private void comboBox(){
        cbBuses.removeAllItems();
        for (int i = 0; i < controlGV.getCaseta().getBuses().size(); i++) {
            cbBuses.addItem(controlGV.getCaseta().getBuses().get(i));
        }
    }
    
    private void limpiarCampos(){
        txtDestino.setText("");
        dateCreacion.setDate(null);
        txtHoraSalida.setText("");
        dateLLegada.setDate(null);
        txtHoraLLegada.setText("");
        cbBuses.setSelectedItem(null);
        txtValorUnidad.setText("");
        txtIdViaje.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaViajes = new javax.swing.JTable();
        lblAdminFlota = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblCaseta = new javax.swing.JLabel();
        lblPlazas = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        Destino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateCreacion = new com.toedter.calendar.JDateChooser();
        lblHoraSalida = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        lblFechaLLegada = new javax.swing.JLabel();
        dateLLegada = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtHoraLLegada = new javax.swing.JTextField();
        lblBus = new javax.swing.JLabel();
        cbBuses = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtValorUnidad = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblIdViaje = new javax.swing.JLabel();
        txtIdViaje = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origen", "Destino", "FechaCreacion", "HoraSalida", "FechaLLegada", "HoraLLegada", "Bus", "ValorUnidad", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaViajes);

        lblAdminFlota.setText("jLabel1");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Gestion de viajes");

        lblId.setText("jLabel2");

        lblCaseta.setText("jLabel3");

        lblPlazas.setText("jLabel4");

        lblOrigen.setText("Origen:");

        txtOrigen.setText("Armenia");

        Destino.setText("Destino:");

        jLabel1.setText("Fecha Creacion:");

        lblHoraSalida.setText("HoraSalida:");

        lblFechaLLegada.setText("Fecha llegada:");

        jLabel2.setText("Hora llegada:");

        lblBus.setText("Bus:");

        jLabel3.setText("Valor unidad:");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblIdViaje.setText("Id viaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAdminFlota)
                                .addGap(106, 106, 106)
                                .addComponent(lblId)
                                .addGap(167, 167, 167)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(lblCaseta)
                                .addGap(130, 130, 130)
                                .addComponent(lblPlazas)
                                .addGap(0, 142, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Destino)
                                            .addComponent(lblOrigen))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                            .addComponent(txtOrigen)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(dateCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblHoraSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFechaLLegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoraSalida)
                                    .addComponent(dateLLegada, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtHoraLLegada))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBus)
                                    .addComponent(jLabel3)
                                    .addComponent(lblIdViaje))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbBuses, 0, 99, Short.MAX_VALUE)
                                    .addComponent(txtValorUnidad)
                                    .addComponent(txtIdViaje)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRegresar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtHoraLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdViaje)
                        .addComponent(txtIdViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAdminFlota)
                                    .addComponent(lblId)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCaseta)
                                        .addComponent(lblPlazas))
                                    .addComponent(lblTitulo))))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrigen)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraSalida)
                            .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBus)
                            .addComponent(cbBuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Destino)
                                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaLLegada))
                                .addComponent(dateLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtValorUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(dateCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar))
                .addGap(15, 15, 15)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaFlota vistaF = new VistaFlota(admiFlota);
        vistaF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        try {
            String origen = txtOrigen.getText();
            String destino = txtDestino.getText();
            LocalDate fechaCreacion = LocalDate.now();
            LocalTime horaSalida = LocalTime.parse(txtHoraSalida.getText());
            Date fecha2 = dateLLegada.getDate();
            LocalDate fechaLlegada = fecha2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalTime horaLlegada = LocalTime.parse(txtHoraLLegada.getText());
            Bus bus = (Bus)cbBuses.getSelectedItem();
            int valorUnidad = Integer.parseInt(txtValorUnidad.getText());
            int idViaje = Integer.parseInt(txtIdViaje.getText());
            Viaje viaje = new Viaje(origen, destino, fechaCreacion, horaSalida,
                    fechaLlegada, horaLlegada, bus, valorUnidad
                    , idViaje);
            controlGV.guardarViaje(viaje);
            JOptionPane.showMessageDialog(null, "El viaje se registro exitosamente");
            llenarTabla();
            limpiarCampos();
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            int idViaje = Integer.parseInt(txtIdViaje.getText());
            controlGV.eliminarViaje(idViaje);
            JOptionPane.showMessageDialog(null, "El viaje se ha eliminado");
            llenarTabla();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Destino;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cbBuses;
    private com.toedter.calendar.JDateChooser dateCreacion;
    private com.toedter.calendar.JDateChooser dateLLegada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminFlota;
    private javax.swing.JLabel lblBus;
    private javax.swing.JLabel lblCaseta;
    private javax.swing.JLabel lblFechaLLegada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdViaje;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblPlazas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaViajes;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtHoraLLegada;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtIdViaje;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtValorUnidad;
    // End of variables declaration//GEN-END:variables
}
