/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Caseta;

/**
 *
 * @author JORGE
 */
public class VistaInfoCaseta extends javax.swing.JFrame {
    private Caseta caseta;
    /**
     * Creates new form VistaInfoCaseta
     */
    public VistaInfoCaseta(Caseta caseta) {
        initComponents();
        setTitle("Informacion de caseta");
        setLocationRelativeTo(this);
        this.caseta = caseta;
        lblEmpresa.setText("Empresa:    " + caseta.getEmpresa().getNombre());
        lblAdministrador.setText("Administrador:    " + caseta.getAdmiFlota().getNombre());
        lblNit.setText("Nit:    " + caseta.getEmpresa().getNit());
        lblArrendamiento.setText("Arrendamiento:    " + caseta.getArrendamiento());
        lblPlazas.setText("Plazas:    " + caseta.getPlazas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblAdministrador = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        lblArrendamiento = new javax.swing.JLabel();
        lblPlazas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Informacion de caseta");

        lblEmpresa.setText("Empresa:");

        lblAdministrador.setText("Administrador:");

        lblNit.setText("Nit:");

        lblArrendamiento.setText("Arrendamiento:");

        lblPlazas.setText("Plazas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpresa)
                            .addComponent(lblTitulo)
                            .addComponent(lblAdministrador)
                            .addComponent(lblNit)
                            .addComponent(lblArrendamiento)
                            .addComponent(lblPlazas))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(51, 51, 51)
                .addComponent(lblEmpresa)
                .addGap(18, 18, 18)
                .addComponent(lblAdministrador)
                .addGap(18, 18, 18)
                .addComponent(lblNit)
                .addGap(18, 18, 18)
                .addComponent(lblArrendamiento)
                .addGap(18, 18, 18)
                .addComponent(lblPlazas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaTerminal vistaT = new VistaTerminal();
        vistaT.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblArrendamiento;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblPlazas;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
